/*연계 세부 로그 테이블*/

CREATE TABLE TBTNS_CON_LOG
(
  CON_LOG_ID     VARCHAR2(15 BYTE)              NOT NULL,
  CON_ID         VARCHAR2(15 BYTE),
  CON_URL        VARCHAR2(1000 BYTE),
  CON_TM         VARCHAR2(5 BYTE),
  CON_KIND_CD    VARCHAR2(10 BYTE),
  LOG_DESC       VARCHAR2(4000 BYTE),
  REG_DT         DATE,
  CON_REWORK_TM  VARCHAR2(5 BYTE),
  WORK_KIND_CD   VARCHAR2(5 BYTE),
  CON_STATUS_CD  VARCHAR2(10 BYTE)
)
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TBTNS_CON_LOG IS 'SERVER와 CLIENT 통신 후 처리된 성공 정보 및 장애 정보에 대한 LOG';

COMMENT ON COLUMN TBTNS_CON_LOG.CON_LOG_ID IS '클라이언트로그아이디 TBTNS_CON_LOG_SEQ.NEXTVAL';

COMMENT ON COLUMN TBTNS_CON_LOG.CON_ID IS '클라이언트아이디';

COMMENT ON COLUMN TBTNS_CON_LOG.CON_URL IS '연계URL';

COMMENT ON COLUMN TBTNS_CON_LOG.CON_TM IS '연계시간';

COMMENT ON COLUMN TBTNS_CON_LOG.CON_KIND_CD IS '연계종류코드 기관-INSTI, 강좌-COURSE, 차시-LESSON';

COMMENT ON COLUMN TBTNS_CON_LOG.LOG_DESC IS '로그설명';

COMMENT ON COLUMN TBTNS_CON_LOG.REG_DT IS '생성일시';

COMMENT ON COLUMN TBTNS_CON_LOG.WORK_KIND_CD IS '작업종류코드 SITE-사이트 연계 PROC-프로시저 데이터작업';



CREATE UNIQUE INDEX PK_TBTNS_CON_LOG ON TBTNS_CON_LOG
(CON_LOG_ID)
LOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBTNS_CON_LOG ADD (
  CONSTRAINT TBTNS_CON_LOG_PK
  PRIMARY KEY
  (CON_LOG_ID)
  USING INDEX PK_TBTNS_CON_LOG
  ENABLE VALIDATE);

