/* 연계기관 테이블 */
CREATE TABLE TBTNS_INSTITUTE_INFO_TRANS
(
  INST_ID                     VARCHAR2(16 BYTE) NOT NULL,
  CON_ID                      VARCHAR2(15 BYTE) NOT NULL,
  TOTAL_CD                    VARCHAR2(10 BYTE),
  SIDO_CD                     VARCHAR2(10 BYTE),
  SIGUNGU_CD                  VARCHAR2(10 BYTE),
  INST_NM                     VARCHAR2(200 BYTE),
  INST_CEO_PERNM              VARCHAR2(200 BYTE),
  INST_SET_UP_MAIN_AGENT_CD   VARCHAR2(2 BYTE),
  INST_OPERATION_FORM_CD      VARCHAR2(2 BYTE),
  ZIPCODE                     VARCHAR2(10 BYTE),
  ADDR1                       VARCHAR2(200 BYTE),
  ADDR2                       VARCHAR2(200 BYTE),
  STREET_CD                   VARCHAR2(12 BYTE),
  STREET_NM                   VARCHAR2(150 BYTE),
  BUILDING_NO                 VARCHAR2(20 BYTE),
  DETAIL_ADDR                 VARCHAR2(200 BYTE),
  MANAGER_PERNM               VARCHAR2(200 BYTE),
  TEL_NO                      VARCHAR2(50 BYTE),
  FAX_NO                      VARCHAR2(20 BYTE),
  EMAIL                       VARCHAR2(200 BYTE),
  HOMEPAGE_URL                VARCHAR2(4000 BYTE),
  INST_DESC                   VARCHAR2(4000 BYTE),
  ESTABLISHMENT_DT            DATE,
  INST_OPERATION_STATUS_CD    VARCHAR2(2 BYTE),
  LONGITUDE_VAL               VARCHAR2(20 BYTE),
  LATITUDE_VAL                VARCHAR2(20 BYTE),
  INFO_MNG_INST_ID            VARCHAR2(100 BYTE),
  INFO_INP_INST_ID            VARCHAR2(100 BYTE),
  TAG                         VARCHAR2(4000 BYTE),
  LOC_LEIC_APPNT_YN           VARCHAR2(1 BYTE),
  LIFE_STUDY_CENTER_APPNT_CD  VARCHAR2(2 BYTE),
  INCUMBENTTRAIN_INST_YN      VARCHAR2(1 BYTE),
  CB_INST_YN                  VARCHAR2(1 BYTE),
  LFLLR_INST_YN               VARCHAR2(1 BYTE),
  PSDC_APPNT_INST_YN          VARCHAR2(1 BYTE),
  BASIC_LIT_EDU_YN            VARCHAR2(1 BYTE),
  ACHV_SPPL_EDU_YN            VARCHAR2(1 BYTE),
  JOB_ABILITY_EDU_YN          VARCHAR2(1 BYTE),
  CULTURE_ART_EDU_YN          VARCHAR2(1 BYTE),
  HUMAN_RFNMNT_EDU_YN         VARCHAR2(1 BYTE),
  CITIZEN_JOIN_EDU_YN         VARCHAR2(1 BYTE),
  INST_CLASS1_CD              VARCHAR2(10 BYTE),
  INST_CLASS2_CD              VARCHAR2(10 BYTE),
  INST_CLASS3_CD              VARCHAR2(50 BYTE),
  REG_USER_ID                 VARCHAR2(30 BYTE),
  REG_DT                      DATE,
  UPD_USER_ID                 VARCHAR2(30 BYTE),
  UPD_DT                      DATE,
  DEL_YN                      VARCHAR2(10 BYTE)
)
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          6M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TBTNS_INSTITUTE_INFO_TRANS IS '연계기관정보전송(기관정보)';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_ID IS '기관아이디';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.CON_ID IS '클라이언트아이디';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.TOTAL_CD IS '토탈코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.SIDO_CD IS '시도코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.SIGUNGU_CD IS '시군구코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_NM IS '기관명';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_CEO_PERNM IS '기관대표자성명';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_SET_UP_MAIN_AGENT_CD IS '기관설립주체코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_OPERATION_FORM_CD IS '기관운영형태코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.ZIPCODE IS '우편번호';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.ADDR1 IS '주소1';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.ADDR2 IS '주소2';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.STREET_CD IS '도로코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.STREET_NM IS '도로명';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.BUILDING_NO IS '건물번호';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.DETAIL_ADDR IS '상세주소';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.MANAGER_PERNM IS '담당자성명';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.TEL_NO IS '전화번호';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.FAX_NO IS '팩스번호';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.EMAIL IS '이메일';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.HOMEPAGE_URL IS '홈페이지URL';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_DESC IS '기관설명';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.ESTABLISHMENT_DT IS '설립일시';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_OPERATION_STATUS_CD IS '기관운영상태코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.LONGITUDE_VAL IS '경도값';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.LATITUDE_VAL IS '위도값';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INFO_MNG_INST_ID IS '정보관리기관코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INFO_INP_INST_ID IS '정보입력기관코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.TAG IS '태그';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.LOC_LEIC_APPNT_YN IS '지역평생교육정보센터지정여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.LIFE_STUDY_CENTER_APPNT_CD IS '평생학습관지정코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INCUMBENTTRAIN_INST_YN IS '직업능력개발훈련기관여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.CB_INST_YN IS '학점은행제평가인정기관여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.PSDC_APPNT_INST_YN IS '학부모지원센터지정기관여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.BASIC_LIT_EDU_YN IS '기초문해교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.ACHV_SPPL_EDU_YN IS '학력보완교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.JOB_ABILITY_EDU_YN IS '직업능력교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.CULTURE_ART_EDU_YN IS '문화예술교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.HUMAN_RFNMNT_EDU_YN IS '인문교양교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.CITIZEN_JOIN_EDU_YN IS '시민참여교육여부';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_CLASS1_CD IS '기관분류1코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_CLASS2_CD IS '기관분류2코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.INST_CLASS3_CD IS '기관분류3코드';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.REG_USER_ID IS '등록자아이디';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.REG_DT IS '등록일시';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.UPD_USER_ID IS '수정자아이디';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.UPD_DT IS '수정일시';

COMMENT ON COLUMN TBTNS_INSTITUTE_INFO_TRANS.DEL_YN IS '삭제여부';



CREATE UNIQUE INDEX PK_TBTNS_INSTITUTE_INFO_TRANS ON TBTNS_INSTITUTE_INFO_TRANS
(CON_ID, INST_ID)
LOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          576K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBTNS_INSTITUTE_INFO_TRANS ADD (
  CONSTRAINT TBTNS_INSTITUTE_INFO_TRANS_PK
  PRIMARY KEY
  (CON_ID, INST_ID)
  USING INDEX PK_TBTNS_INSTITUTE_INFO_TRANS
  ENABLE VALIDATE);

