from django.db import models

class Course_info(models.Model):
    class Meta:
        db_table = "TBTNS_COURSE_INFO_TRANS"
        unique_together = (('course_id', 'con_id'),)
    course_id = models.CharField(primary_key=True, max_length=32)
    con_id = models.CharField(max_length=15)
    inst_id = models.CharField(null=True, max_length=16)
    total_cd = models.CharField(null=True, max_length=16)
    sido_cd = models.CharField(null=True, max_length=10)
    sigungu_cd = models.CharField(null=True, max_length=10)
    course_nm = models.CharField(null=True, max_length=500)
    course_desc_url = models.CharField(null=True, max_length=2000) 
    course_pttn_cd = models.CharField(null=True, max_length=2)
    extra_charge_content = models.CharField(null=True, max_length=200)
    edu_cycle_content = models.CharField(null=True, max_length=200)
    edu_quota_cnt = models.CharField(null=True, max_length=200)
    course_start_dt = models.DateTimeField(null=True)
    course_end_dt = models.DateTimeField(null=True)
    receive_start_dt = models.DateTimeField(null=True)
    receive_end_dt = models.DateTimeField(null=True)
    edu_tm = models.CharField(null=True, max_length=200)
    edu_location_desc = models.CharField(null=True, max_length=2000)
    inquiry_tel_no = models.CharField(null=True, max_length=100)
    teacher_pernm = models.CharField(null=True, max_length=200)
    info_mng_inst_id = models.CharField(null=True, max_length=100)
    info_inp_inst_id = models.CharField(null=True, max_length=100)
    reg_user_id = models.CharField(null=True, max_length=30)
    reg_dt = models.DateTimeField(null=True)
    upd_user_id = models.CharField(null=True, max_length=20)
    upd_dt = models.DateTimeField(null=True)
    tag = models.CharField(null=True, max_length=2000)
    job_ability_course_yn = models.CharField(null=True, max_length=1)
    cb_eval_accept_yn = models.CharField(null=True, max_length=1)
    all_eval_accept_yn = models.CharField(null=True, max_length=1)
    lang_cd = models.CharField(null=True, max_length=10)
    study_os_nm = models.CharField(null=True, max_length=200)
    study_web_browser_nm = models.CharField(null=True, max_length=100)
    study_device_nm = models.CharField(null=True, max_length=100)
    vsl_handicap_supp_yn = models.CharField(null=True, max_length=1)
    hrg_handicap_supp_yn = models.CharField(null=True, max_length=1)
    course_class1_cd = models.CharField(null=True, max_length=30)
    course_class2_cd = models.CharField(null=True, max_length=30)
    course_thumbnail_url = models.CharField(null=True, max_length=2000)
    edu_target_cd = models.CharField(null=True, max_length=200)
    enroll_appl_method_cd = models.CharField(null=True, max_length=50)
    edu_method_cd = models.CharField(null=True, max_length=10)
    edu_lvldff_type_cd = models.CharField(null=True, max_length=10)
    ref_book_nm = models.CharField(null=True, max_length=200)
    source_desc = models.CharField(null=True, max_length=2000)
    link_url = models.CharField(null=True, max_length=2000)
    del_yn = models.CharField(null=True, max_length=1)
    course_url = models.CharField(null=True, max_length=2000)
    course_url_call_method = models.CharField(null=True, max_length=10)
    mobile_url = models.CharField(null=True, max_length=2000)
    mobile_url_call_method = models.CharField(null=True, max_length=10)
    course_desc = models.CharField(null=True, max_length=2000)
    enroll_amt = models.CharField(null=True, max_length=200)

class Inst_info(models.Model):
    class Meta:
        db_table = "TBTNS_INSTITUTE_INFO_TRANS"
        unique_together = (('inst_id', 'con_id'),)
    inst_id = models.CharField(primary_key=True, max_length=16)
    con_id = models.CharField(max_length=15)
    total_cd = models.CharField(null=True, max_length=16)
    sido_cd = models.CharField(null=True, max_length=10)
    sigungu_cd = models.CharField(null=True, max_length=10)
    inst_nm = models.CharField(null=True, max_length=200)
    inst_ceo_pernm = models.CharField(null=True, max_length=200)
    inst_set_up_main_agent_cd = models.CharField(null=True, max_length=2)
    inst_operation_form_cd = models.CharField(null=True, max_length=2)
    zipcode = models.CharField(null=True, max_length=10)
    addr1 = models.CharField(null=True, max_length=200)
    addr2 = models.CharField(null=True, max_length=200)
    street_cd = models.CharField(null=True, max_length=12)
    street_nm = models.CharField(null=True, max_length=150)
    building_no = models.CharField(null=True, max_length=20)
    detail_addr = models.CharField(null=True, max_length=200)
    manager_pernm = models.CharField(null=True, max_length=200)
    tel_no = models.CharField(null=True, max_length=50)
    fax_no = models.CharField(null=True, max_length=20)
    email = models.CharField(null=True, max_length=200)
    homepage_url = models.CharField(null=True, max_length=2000)
    inst_desc = models.CharField(null=True, max_length=2000)
    establishment_dt = models.DateField(null=True)
    inst_operation_status_cd = models.CharField(null=True, max_length=2)
    longitude_val = models.CharField(null=True, max_length=20)
    latitude_val = models.CharField(null=True, max_length=20)
    info_mng_inst_id = models.CharField(null=True, max_length=100)
    info_inp_inst_id = models.CharField(null=True, max_length=100)
    tag = models.CharField(null=True, max_length=2000)
    loc_leic_appnt_yn = models.CharField(null=True, max_length=1)
    life_study_center_appnt_cd = models.CharField(null=True, max_length=2)
    incumbenttrain_inst_yn = models.CharField(null=True, max_length=1)
    cb_inst_yn = models.CharField(null=True, max_length=1)
    lfllr_inst_yn = models.CharField(null=True, max_length=1)
    psdc_appnt_inst_yn = models.CharField(null=True, max_length=1)
    basic_lit_edu_yn = models.CharField(null=True, max_length=1)
    achv_sppl_edu_yn = models.CharField(null=True, max_length=1)
    job_ability_edu_yn = models.CharField(null=True, max_length=1)
    culture_art_edu_yn = models.CharField(null=True, max_length=1)
    human_rfnmnt_edu_yn = models.CharField(null=True, max_length=1)
    citizen_join_edu_yn = models.CharField(null=True, max_length=1)
    inst_class1_cd = models.CharField(null=True, max_length=10)
    inst_class2_cd = models.CharField(null=True, max_length=10)
    inst_class3_cd = models.CharField(null=True, max_length=50)
    reg_user_id = models.CharField(null=True, max_length=30)
    reg_dt = models.DateField(null=True)
    upd_user_id = models.CharField(null=True, max_length=30)
    upd_dt = models.DateField(null=True)
    del_yn = models.CharField(null=True, max_length=10, default='N')

class Con_log(models.Model):
    class Meta:
        db_table = "TBTNS_CON_LOG"
    con_log_id = models.CharField(primary_key=True, max_length=15)
    con_id = models.CharField(null=True, max_length=15)
    con_url = models.CharField(null=True, max_length=1000)
    con_tm = models.CharField(null=True, max_length=5)
    con_kind_cd = models.CharField(null=True, max_length=10)
    log_desc = models.CharField(null=True, max_length=2000)
    reg_dt = models.DateTimeField(null=True)
    con_rework_tm = models.CharField(null=True, max_length=5)
    work_kind_cd = models.CharField(null=True, max_length=5, default='SITE')
    con_status_cd = models.CharField(null=True, max_length=5, default='ERROR')
